# title: Sen Li's Homepage
# page-top-title: Sen Li
# top-section-bg-text: Computer Science
# home-subtitle: Sen Li&ensp;|&ensp;李森
# copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'

# Site settings
title: "Shaoguang WANG's Homepage"
name: "Shaoguang WANG"
email: "shaoguangwang9@gmail.com"
github: "<https://github.com/shaoguangwang>"
scholar: "https://scholar.google.com/citations?hl=en&user=WBhTMFAAAAAJ"
copyright: "Copyright Shaoguang WANG, 2025. This website is adapted from a template by Sen Li."